In [2]:
import pandas as pd
#Pandas = panel data

In [3]:
x = pd.__version__
print(x)

2.3.3

Series and Dataframes are the objects pandas package basically works with

Series is a 1D array which is labeled and can hold any data type

just like a column in a spreadsheet

In [4]:
data_test= [1, 2, 3, 4, 5]
series = pd.Series(data_test, index=['a', 'b', 'c', 'd', 'e'])
print(series.loc['a'])

1

loc is locaton by label 

What it accepts -	Row/Column names (strings or integers) 

Slicing behavior	Inclusive of the end bound (e.g., loc[1:3] includes 3)

iloc is location by integer

Integer positions only (0 to length-1)

Exclusive of the end bound (e.g., iloc[1:3] stops at 2)

both use the subscript operator "[ ]"

In [5]:
print(series.iloc[0])

1

Finding the value in the series that is greater than 2

In [6]:
print(series[series > 2])

c    3
d    4
e    5
dtype: int64

A dictionary if is passed into series constructor, it will use the key of dictionary as index automatically

In [7]:
calories= {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

day1    420
day2    380
day3    390
dtype: int64

Dataframe - 2d tabular data structure 

like a full excel spreadhseet

In [8]:
data_2d= {"Name": ['Alice', 'Bob', 'Charlie'], "Age": [25, 30, 35], "City": ['New York', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data_2d)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [9]:
data_2d= {"Name": ['Alice', 'Bob', 'Charlie'], "Age": [25, 30, 35], "City": ['New York', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data_2d, index=['row1', 'row2', 'row3'])
print(df)

         Name  Age         City
row1    Alice   25     New York
row2      Bob   30  Los Angeles
row3  Charlie   35      Chicago

In [ ]:
#new row? we just add a new row by making another df and concatenating
#a list of of dictionaries will be used and the key values will be column names and values will be the the new values to be added.

new_row =pd.DataFrame([{"Name": "David", "Age": 40, "City": "Houston"}, {"Name": "Eva", "Age": 28, "City": "Seattle"}]) 
df1=pd.concat([df,new_row],ignore_index=True)
print(df1)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   28      Seattle

In [15]:
#add a new column
df1["Country"] = ["USA", "Canada", "UK", "Australia", "Germany"]
print(df1)

      Name  Age         City    Country
0    Alice   25     New York        USA
1      Bob   30  Los Angeles     Canada
2  Charlie   35      Chicago         UK
3    David   40      Houston  Australia
4      Eva   28      Seattle    Germany

Working with CSV and Importing

In [18]:
dfpok= pd.read_csv(r"C:\Users\manan\OneDrive\Desktop\Data for pokemon.csv", index_col=0)
dfpok.head(10)

          Name  Type1   Type2  Height  Weight  Legendary
No
1    Bulbasaur  Grass  Poison     0.7     6.9          0
2      Ivysaur  Grass  Poison     1.0    13.0          0
3     Venusaur  Grass  Poison     2.0   100.0          0
4   Charmander   Fire     NaN     0.6     8.5          0
5   Charmeleon   Fire     NaN     1.1    19.0          0
6    Charizard   Fire  Flying     1.7    90.5          0
7     Squirtle  Water     NaN     0.5     9.0          0
8    Wartortle  Water     NaN     1.0    22.5          0
9    Blastoise  Water     NaN     1.6    85.5          0
10    Caterpie    Bug     NaN     0.3     2.9          0

Selection Techniques

In [21]:
#Selection by columns
print(dfpok["Name"].to_string())
print(dfpok["Name"])

No
1       Bulbasaur
2         Ivysaur
3        Venusaur
4      Charmander
5      Charmeleon
6       Charizard
7        Squirtle
8       Wartortle
9       Blastoise
10       Caterpie
11        Metapod
12     Butterfree
13         Weedle
14         Kakuna
15       Beedrill
16         Pidgey
17      Pidgeotto
18        Pidgeot
19        Rattata
20       Raticate
21        Spearow
22         Fearow
23          Ekans
24          Arbok
25        Pikachu
26         Raichu
27      Sandshrew
28      Sandslash
29       Nidoran♀
30       Nidorina
31      Nidoqueen
32       Nidoran♂
33       Nidorino
34       Nidoking
35       Clefairy
36       Clefable
37         Vulpix
38      Ninetales
39     Jigglypuff
40     Wigglytuff
41          Zubat
42         Golbat
43         Oddish
44          Gloom
45      Vileplume
46          Paras
47       Parasect
48        Venonat
49       Venomoth
50        Diglett
51        Dugtrio
52         Meowth
53        Persian
54        Psyduck
55        Golduck
56         Mankey
57       Primeape
58      Growlithe
59       Arcanine
60        Poliwag
61      Poliwhirl
62      Poliwrath
63           Abra
64        Kadabra
65       Alakazam
66         Machop
67        Machoke
68        Machamp
69     Bellsprout
70     Weepinbell
71     Victreebel
72      Tentacool
73     Tentacruel
74        Geodude
75       Graveler
76          Golem
77         Ponyta
78       Rapidash
79       Slowpoke
80        Slowbro
81      Magnemite
82       Magneton
83     Farfetch'd
84          Doduo
85         Dodrio
86           Seel
87        Dewgong
88         Grimer
89            Muk
90       Shellder
91       Cloyster
92         Gastly
93        Haunter
94         Gengar
95           Onix
96        Drowzee
97          Hypno
98         Krabby
99        Kingler
100       Voltorb
101     Electrode
102     Exeggcute
103     Exeggutor
104        Cubone
105       Marowak
106     Hitmonlee
107    Hitmonchan
108     Lickitung
109       Koffing
110       Weezing
111       Rhyhorn
112        Rhydon
113       Chansey
114       Tangela
115    Kangaskhan
116        Horsea
117        Seadra
118       Goldeen
119       Seaking
120        Staryu
121       Starmie
122      Mr. Mime
123       Scyther
124          Jynx
125    Electabuzz
126        Magmar
127        Pinsir
128        Tauros
129      Magikarp
130      Gyarados
131        Lapras
132         Ditto
133         Eevee
134      Vaporeon
135       Jolteon
136       Flareon
137       Porygon
138       Omanyte
139       Omastar
140        Kabuto
141      Kabutops
142    Aerodactyl
143       Snorlax
144      Articuno
145        Zapdos
146       Moltres
147       Dratini
148     Dragonair
149     Dragonite
150        Mewtwo
No
1       Bulbasaur
2         Ivysaur
3        Venusaur
4      Charmander
5      Charmeleon
          ...
146       Moltres
147       Dratini
148     Dragonair
149     Dragonite
150        Mewtwo
Name: Name, Length: 150, dtype: object

In [23]:
print(dfpok[["Name", "Type1"]])

           Name    Type1
No
1     Bulbasaur    Grass
2       Ivysaur    Grass
3      Venusaur    Grass
4    Charmander     Fire
5    Charmeleon     Fire
..          ...      ...
146     Moltres     Fire
147     Dratini   Dragon
148   Dragonair   Dragon
149   Dragonite   Dragon
150      Mewtwo  Psychic

[150 rows x 2 columns]

In [26]:
print(dfpok.iloc[0])

Name         Bulbasaur
Type1            Grass
Type2           Poison
Height             0.7
Weight             6.9
Legendary            0
Name: 1, dtype: object

In [30]:
dfpok.loc[dfpok['Type1'] == 'Water']

           Name  Type1     Type2  Height  Weight  Legendary
No
7      Squirtle  Water       NaN     0.5     9.0          0
8     Wartortle  Water       NaN     1.0    22.5          0
9     Blastoise  Water       NaN     1.6    85.5          0
54      Psyduck  Water       NaN     0.8    19.6          0
55      Golduck  Water       NaN     1.7    76.6          0
60      Poliwag  Water       NaN     0.6    12.4          0
61    Poliwhirl  Water       NaN     1.0    20.0          0
62    Poliwrath  Water  Fighting     1.3    54.0          0
72    Tentacool  Water    Poison     0.9    45.5          0
73   Tentacruel  Water    Poison     1.6    55.0          0
79     Slowpoke  Water   Psychic     1.2    36.0          0
80      Slowbro  Water   Psychic     1.6    78.5          0
86         Seel  Water       NaN     1.1    90.0          0
87      Dewgong  Water       Ice     1.7   120.0          0
90     Shellder  Water       NaN     0.3     4.0          0
91     Cloyster  Water       Ice     1.5   132.5          0
98       Krabby  Water       NaN     0.4     6.5          0
99      Kingler  Water       NaN     1.3    60.0          0
116      Horsea  Water       NaN     0.4     8.0          0
117      Seadra  Water       NaN     1.2    25.0          0
118     Goldeen  Water       NaN     0.6    15.0          0
119     Seaking  Water       NaN     1.3    39.0          0
120      Staryu  Water       NaN     0.8    34.5          0
121     Starmie  Water   Psychic     1.1    80.0          0
129    Magikarp  Water       NaN     0.9    10.0          0
130    Gyarados  Water    Flying     6.5   235.0          0
131      Lapras  Water       Ice     2.5   220.0          0
134    Vaporeon  Water       NaN     1.0    29.0          0

In [35]:
print(dfpok.loc[0:10][dfpok['Type1'] == 'Water'])

#or use query function to chain

print(dfpok.loc[0:10].query("Type1 == 'Water'"))

         Name  Type1 Type2  Height  Weight  Legendary
No
7    Squirtle  Water   NaN     0.5     9.0          0
8   Wartortle  Water   NaN     1.0    22.5          0
9   Blastoise  Water   NaN     1.6    85.5          0
         Name  Type1 Type2  Height  Weight  Legendary
No
7    Squirtle  Water   NaN     0.5     9.0          0
8   Wartortle  Water   NaN     1.0    22.5          0
9   Blastoise  Water   NaN     1.6    85.5          0

C:\Users\manan\AppData\Local\Temp\ipykernel_1268\1418035673.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(dfpok.loc[0:10][dfpok['Type1'] == 'Water'])

In [ ]:
#searching for a pokemon by number

Pokemon= input("Enter the number of the pokemon you want to search: ")
try:
    print(dfpok.loc[int(Pokemon)])
except KeyError:
    print("Pokemon not found. Please enter a valid number.")

Name         Ivysaur
Type1          Grass
Type2         Poison
Height           1.0
Weight          13.0
Legendary          0
Name: 2, dtype: object

Filtering